# A sample Guardfile
# More info at https://github.com/guard/guard#readme
guard 'coffeescript', :output => 'spec/javascripts/compiled/lib' do
  watch(/^app\/assets\/javascripts\/(.*).coffee/)
end

guard 'coffeescript', :output => 'spec/javascripts/compiled/spec' do
  watch(/^spec\/javascripts\/(.*).coffee/)
end
